FROM labtainers/labtainer.base2:latest
LABEL version="1.0" base="labtainers/labtainer.base2.739eee77f8d3"
ARG lab
ARG labdir
ARG imagedir
ENV HOME /home/ubuntu
USER root
RUN useradd -m -s /bin/bash ubuntu || true
WORKDIR /home/ubuntu
ADD $labdir/$lab.tar.gz /home/ubuntu
RUN chown -R ubuntu:ubuntu /home/ubuntu && chmod +x /home/ubuntu/stego/*.py
